### ISSUE TITLE
To Do Yeo, Eunseong

### ISSUE THREAD

**Issue by YeoEunSeong** [ktmihs/git-study#3]
혼자 하는 git flow process
- [x] 초기화 : git flow를 초기화 명령어, git flow를 초기화 했을 때 변경점
- [x] 기능 개발 : 기능 개발 명령어, 명령어 실행시 변경점
- [x] release: release 명령어, 명령어 실행시 변경점
- [x] master 병합
- [x] 명령어 모음 정리: git flow process에서 사용되는 명령어 모음

**Comment by ktmihs** [comment]
은성님 풀리퀘 언제 하세요 ?

**Comment by YeoEunSeong** [comment]
> 은성님 풀리퀘 언제 하세요 ?

지금요

**Comment by ktmihs** [comment]
충돌해결했어요 패치 다시해주세요!
